using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
namespace PvZSymbiosisTranslator.UI;
public static class ModLabels
{
    private static readonly Dictionary<string,string> Overrides=new(StringComparer.Ordinal);
    public static Dictionary<string,string> LoadCandidate(string localeDirectory,Action<string> warning=null) {
        var next=new Dictionary<string,string>(StringComparer.Ordinal);var path=Path.Combine(localeDirectory,"ModStrings.json");
        if(!File.Exists(path)) path=Path.Combine(localeDirectory,"mod_ui.json");
        if(!File.Exists(path)) throw new FileNotFoundException("Required ModStrings file missing",path);
        using(var doc=Localization.JsonFile.Read(path,warning)) {
            if(doc.RootElement.ValueKind!=JsonValueKind.Object) throw new FormatException("ModStrings must be a JSON object");
            foreach(var item in doc.RootElement.EnumerateObject()) {
                if(item.Value.ValueKind!=JsonValueKind.String || string.IsNullOrWhiteSpace(item.Value.GetString())) throw new FormatException("Empty/non-string ModStrings value: "+item.Name);
                if(!next.TryAdd(item.Name,item.Value.GetString())) throw new FormatException("Duplicate ModStrings key: "+item.Name);
            }
        }
        var template=Path.Combine(Directory.GetParent(localeDirectory)?.FullName ?? "","_template","ModStrings.json");
        if(File.Exists(template)) using(var canonical=Localization.JsonFile.Read(template,warning)) {
            foreach(var item in canonical.RootElement.EnumerateObject()) if(!next.ContainsKey(item.Name)) throw new FormatException("Missing ModStrings key: "+item.Name);
        }
        return next;
    }
    public static void Apply(IReadOnlyDictionary<string,string> candidate) {
        if(candidate==null) throw new ArgumentNullException(nameof(candidate));
        Overrides.Clear();foreach(var item in candidate) Overrides.Add(item.Key,item.Value);
    }
    public static void Load(string localeDirectory) {
        Apply(LoadCandidate(localeDirectory));
    }
    private static readonly Dictionary<string,string> Portuguese = new(StringComparer.Ordinal) {
        ["diagnostics.runtime"]="RUNTIME", ["diagnostics.health"]="SAÚDE DA INTEGRAÇÃO", ["diagnostics.live"]="ESTADO AO VIVO", ["diagnostics.ui"]="SAÚDE DA INTERFACE", ["diagnostics.actions"]="AÇÕES", ["diagnostics.refresh"]="Atualizar diagnóstico", ["diagnostics.copy"]="Copiar diagnóstico", ["diagnostics.export"]="Exportar diagnóstico", ["diagnostics.openLogs"]="Abrir log", ["diagnostics.openMod"]="Abrir pasta do mod", ["diagnostics.openExports"]="Abrir exportações", ["diagnostics.unavailable"]="Diagnóstico ainda não disponível.", ["diagnostics.mod"]="Versão do mod", ["diagnostics.game"]="Versão do jogo", ["diagnostics.language"]="Idioma ativo", ["diagnostics.scene"]="Cena", ["diagnostics.context"]="Contexto", ["diagnostics.features"]="Recursos", ["diagnostics.observed"]="Strings observadas", ["diagnostics.translated"]="Traduzidas", ["diagnostics.preserved"]="Preservadas", ["diagnostics.unknown"]="Desconhecidas", ["diagnostics.watched"]="Arquivos observados", ["diagnostics.lastChange"]="Última alteração", ["diagnostics.autoReload"]="Auto-reload", ["diagnostics.manualReload"]="Recarga manual", ["diagnostics.reload"]="Última recarga", ["diagnostics.lastError"]="Último erro", ["diagnostics.canvas"]="Canvas do tradutor", ["diagnostics.settings"]="Janela", ["diagnostics.tab"]="Aba", ["diagnostics.launchers"]="Botões iniciais", ["diagnostics.roots"]="Raízes da janela", ["diagnostics.check.translationStore"]="TranslationStore", ["diagnostics.check.exactStore"]="ExactStringStore", ["diagnostics.check.contextOverrides"]="Substituições por contexto", ["diagnostics.check.dynamicRules"]="Regras dinâmicas", ["diagnostics.check.collector"]="Coletor de strings", ["diagnostics.check.font"]="Sistema de fontes", ["diagnostics.check.textures"]="TextureStore", ["diagnostics.check.audio"]="AudioStore", ["diagnostics.check.watcher"]="Watcher de arquivos", ["diagnostics.check.settingsUi"]="Interface de configurações", ["diagnostics.check.harmony"]="Patches Harmony", ["diagnostics.check.exports"]="Diretório de exportação", ["diagnostics.check.languageDirectory"]="Diretório do idioma", ["diagnostics.check.translatorCanvas"]="Canvas extra", ["diagnostics.check.launcher"]="Botão inicial", ["diagnostics.check.settingsRoots"]="Raiz de configurações", ["status.diagnosticsRefreshed"]="Diagnóstico atualizado.", ["status.diagnosticsCopied"]="Diagnóstico copiado.", ["status.diagnosticsExported"]="Diagnóstico exportado.",
        ["translator.preserved"]="Preservadas explicitamente",
        ["qa.summary"]="RESUMO DE QA", ["qa.checks"]="VERIFICAÇÕES DE QUALIDADE", ["qa.issues"]="ACHADOS", ["qa.actions"]="AÇÕES", ["qa.run"]="Executar QA completo", ["qa.exportReport"]="Exportar relatório", ["qa.exportUnresolved"]="Exportar pendências", ["qa.openExports"]="Abrir exportações", ["qa.copySummary"]="Copiar resumo", ["qa.notScanned"]="A verificação ainda não foi executada.", ["qa.overall"]="Estado geral", ["qa.errors"]="Erros", ["qa.warnings"]="Avisos", ["qa.info"]="Informações", ["qa.exact"]="Traduções exatas", ["qa.dynamic"]="Regras dinâmicas", ["qa.contexts"]="Substituições por contexto", ["qa.runtime"]="Strings observadas", ["qa.unknown"]="Desconhecidas", ["qa.lastScan"]="Última verificação", ["qa.noImportantIssues"]="Nenhum problema importante encontrado.", ["qa.status.pass"]="PASS", ["qa.status.warn"]="AVISO", ["qa.status.fail"]="FALHA", ["qa.status.info"]="INFO", ["qa.status.na"]="N/D", ["qa.check.json"]="Integridade JSON", ["qa.check.placeholders"]="Placeholders", ["qa.check.markup"]="Tags TMP", ["qa.check.dynamic"]="Regras dinâmicas", ["qa.check.conflicts"]="Duplicatas e conflitos", ["qa.check.cjk"]="Resíduos CJK", ["qa.check.whitespace"]="Espaços e controles", ["qa.check.length"]="Risco de comprimento", ["qa.check.encoding"]="Codificação", ["qa.check.textures"]="Manifesto de texturas", ["qa.check.audio"]="Manifesto de áudio", ["qa.check.paths"]="Caminhos do pacote", ["qa.check.contamination"]="Fonte e renderização", ["status.qaComplete"]="Verificação de QA concluída.", ["status.qaExported"]="Relatório de QA exportado.", ["status.qaSummaryCopied"]="Resumo de QA copiado.",
        ["translator.settings"]="CONFIGURAÇÕES DO TRADUTOR", ["translator.session"]="SESSÃO ATUAL", ["translator.actions"]="AÇÕES RÁPIDAS", ["translator.exports"]="EXPORTAÇÃO", ["translator.mode"]="Modo de tradutor", ["translator.debug"]="Logs detalhados", ["translator.autoReload"]="Auto-recarregar arquivos", ["translator.validateBeforeApply"]="Validar antes de aplicar", ["translator.captureUnknown"]="Capturar textos desconhecidos", ["translator.autoExport"]="Auto-exportar ao trocar de tela", ["translator.detailedContext"]="Contexto detalhado", ["translator.reloadNow"]="Recarregar agora", ["translator.refreshCurrentScreen"]="Atualizar tela atual", ["translator.clearCapture"]="Limpar captura", ["translator.copySessionSummary"]="Copiar resumo", ["translator.exportUntranslated"]="Exportar não traduzidos", ["translator.exportCurrentScreen"]="Exportar tela atual", ["translator.exportSession"]="Exportar sessão", ["translator.openExports"]="Abrir exportações", ["translator.currentContext"]="Contexto atual", ["translator.scene"]="Cena observada", ["translator.uniqueSeen"]="Strings únicas vistas", ["translator.runtimeTranslated"]="Traduzidas em execução", ["translator.knownUntranslated"]="Conhecidas sem tradução", ["translator.runtimeUnknown"]="Desconhecidas em execução", ["translator.sessionUnknown"]="Capturadas nesta sessão", ["translator.watchedFiles"]="Arquivos observados", ["translator.lastChange"]="Última alteração", ["translator.lastAutoReload"]="Último auto-reload", ["translator.watcher"]="Status do watcher", ["translator.shortcutsInfo"]="Insert — tradução  •  PageUp — recarregar  •  PageDown — exportar\nF8 / F9 / F10 — sem uso pelo tradutor", ["translator.watcherActive"]="ATIVO", ["translator.watcherDisabled"]="DESATIVADO", ["translator.watcherError"]="ERRO", ["status.autoReloadEnabled"]="Auto-reload ativado.", ["status.autoReloadDisabled"]="Auto-reload desativado.", ["status.settingSaved"]="Configuração salva.", ["status.screenRefreshed"]="Tela atual atualizada.", ["status.captureCleared"]="Captura limpa.", ["status.summaryCopied"]="Resumo da sessão copiado.", ["status.untranslatedExported"]="Textos não traduzidos exportados.", ["status.sessionExported"]="Sessão exportada.", ["status.autoReloaded"]="Traduções recarregadas automaticamente.",
        ["content.activePackSection"]="PACOTE ATIVO", ["content.reloadSection"]="RECARREGAR", ["content.lastReloadSection"]="ÚLTIMA RECARGA", ["content.foldersSection"]="PASTAS", ["content.activeLanguage"]="Idioma ativo", ["content.folder"]="Pasta", ["content.primaryFont"]="Fonte principal", ["content.fallback"]="Fallback", ["content.exact"]="Traduções exatas", ["content.dynamic"]="Regras dinâmicas", ["content.textures"]="Texturas mapeadas", ["content.audio"]="Áudios mapeados", ["content.installedLocales"]="Idiomas instalados", ["content.result"]="Resultado", ["content.time"]="Horário", ["content.duration"]="Duração", ["content.files"]="Arquivos processados", ["content.errors"]="Erros", ["content.never"]="Ainda não executada", ["content.pass"]="PASS", ["content.fail"]="FALHA", ["content.milliseconds"]="ms", ["actions.reloadTexts"]="Recarregar textos", ["actions.openTexturesFolder"]="Abrir texturas", ["actions.openAudioFolder"]="Abrir áudio", ["status.reloadPreserved"]="Falha na recarga — tradução anterior preservada.",
        ["common.enabled"]="Ativado", ["common.disabled"]="Desativado", ["general.languageSection"]="IDIOMA", ["general.translationSection"]="TRADUÇÃO", ["general.interfaceSection"]="INTERFACE", ["general.statusSection"]="ESTADO GERAL", ["general.language"]="Idioma", ["general.translation"]="Tradução de textos", ["general.font"]="Fonte personalizada", ["general.textures"]="Texturas traduzidas", ["general.audio"]="Áudio personalizado", ["general.notifications"]="Notificações da interface", ["general.uiScale"]="Escala da interface", ["general.pack"]="Pacote", ["general.version"]="Versão",
        ["translator"]="Modo de tradutor", ["translatorHint"]="PageDown: exportar textos e contextos", ["texts"]="Textos", ["languages"]="Idiomas", ["title"]="Configurações de Idioma", ["language"]="Idioma", ["translation"]="Tradução", ["font"]="Fonte personalizada", ["textures"]="Texturas traduzidas", ["audio"]="Áudio personalizado", ["reload"]="Recarregar", ["export"]="Exportar textos", ["close"]="Fechar", ["on"]="Ativada", ["off"]="Desativada", ["translationEnabled"]="Tradução ativada", ["translationDisabled"]="Tradução desativada", ["reloaded"]="Traduções recarregadas", ["reloadFailed"]="Falha ao recarregar traduções", ["exported"]="Diagnóstico de tradução exportado",
        ["menu.languages"]="Idiomas", ["menu.title"]="Configurações do Tradutor", ["tabs.qa"]="QA", ["common.close"]="Fechar", ["settings.title"]="Configurações do Tradutor", ["settings.language"]="Idioma", ["settings.translation"]="Tradução de textos", ["settings.font"]="Fonte personalizada", ["settings.textures"]="Texturas traduzidas", ["settings.audio"]="Áudio personalizado", ["settings.translatorMode"]="Modo de tradutor", ["settings.debugLogging"]="Logs de depuração", ["settings.enabled"]="Ativada", ["settings.disabled"]="Desativada", ["settings.enabledPlural"]="Ativadas", ["settings.disabledPlural"]="Desativadas", ["settings.enabledMasculine"]="Ativado", ["settings.disabledMasculine"]="Desativado", ["settings.reload"]="Recarregar tradução", ["settings.export"]="Exportar diagnóstico", ["settings.close"]="Fechar", ["settings.packStatus"]="Pacote carregado", ["tabs.general"]="Geral", ["tabs.content"]="Conteúdo", ["tabs.translator"]="Tradutor", ["tabs.diagnostics"]="Diagnóstico", ["sections.language"]="IDIOMA", ["sections.translation"]="TRADUÇÃO", ["sections.status"]="ESTADO GERAL", ["sections.fonts"]="FONTES E CONTEÚDO", ["sections.hotkeys"]="ATALHOS", ["actions.reloadAll"]="Recarregar tudo", ["actions.reloadFonts"]="Recarregar fontes", ["actions.reloadTextures"]="Recarregar texturas", ["actions.reloadAudio"]="Recarregar áudio", ["actions.exportUntranslated"]="Exportar não traduzidos", ["actions.exportDiagnostics"]="Exportar diagnóstico", ["actions.exportCurrentScene"]="Exportar tela atual", ["actions.openLocaleFolder"]="Abrir pasta do idioma", ["actions.openExportFolder"]="Abrir exportações", ["actions.openModFolder"]="Abrir pasta do mod", ["actions.openLogs"]="Abrir logs", ["status.reloaded"]="Traduções recarregadas", ["status.reloadFailed"]="Falha ao recarregar traduções", ["status.exported"]="Diagnóstico exportado", ["status.sceneExported"]="Textos da tela exportados", ["status.folderOpened"]="Pasta aberta", ["status.actionFailed"]="A ação falhou; consulte o log", ["status.onlyLocale"]="Único idioma completo instalado", ["stats.version"]="Versão do tradutor", ["stats.gameVersion"]="Versão do jogo", ["stats.unityVersion"]="Versão do Unity", ["stats.melonVersion"]="Versão do MelonLoader", ["stats.locale"]="Idioma", ["stats.exact"]="Exatas", ["stats.dynamic"]="Dinâmicas", ["stats.rejected"]="Rejeitadas", ["stats.warnings"]="Avisos", ["stats.known"]="Não traduzidas conhecidas", ["stats.unknown"]="Desconhecidas em execução", ["stats.font"]="Fonte principal", ["stats.fallbackFonts"]="Fontes alternativas", ["stats.textureMappings"]="Mapeamentos de textura", ["stats.audioMappings"]="Mapeamentos de áudio", ["stats.translatorCanvas"]="Canvas do tradutor", ["stats.context"]="Contexto visível", ["hotkeys.toggleTranslation"]="Ativar/desativar tradução", ["hotkeys.reload"]="Recarregar", ["hotkeys.export"]="Exportar"
    };
    private static readonly Dictionary<string,string> English = new(StringComparer.Ordinal) {
        ["diagnostics.runtime"]="RUNTIME", ["diagnostics.health"]="INTEGRATION HEALTH", ["diagnostics.live"]="LIVE STATE", ["diagnostics.ui"]="UI HEALTH", ["diagnostics.actions"]="ACTIONS", ["diagnostics.refresh"]="Refresh diagnostics", ["diagnostics.copy"]="Copy diagnostics", ["diagnostics.export"]="Export diagnostics", ["diagnostics.openLogs"]="Open log", ["diagnostics.openMod"]="Open mod folder", ["diagnostics.openExports"]="Open exports", ["diagnostics.unavailable"]="Diagnostics are not available yet.", ["diagnostics.mod"]="Mod version", ["diagnostics.game"]="Game version", ["diagnostics.language"]="Active language", ["diagnostics.scene"]="Scene", ["diagnostics.context"]="Context", ["diagnostics.features"]="Features", ["diagnostics.observed"]="Observed strings", ["diagnostics.translated"]="Translated", ["diagnostics.preserved"]="Preserved", ["diagnostics.unknown"]="Unknown", ["diagnostics.watched"]="Watched files", ["diagnostics.lastChange"]="Last change", ["diagnostics.autoReload"]="Auto-reload", ["diagnostics.manualReload"]="Manual reload", ["diagnostics.reload"]="Last reload", ["diagnostics.lastError"]="Last error", ["diagnostics.canvas"]="Translator Canvas", ["diagnostics.settings"]="Settings window", ["diagnostics.tab"]="Tab", ["diagnostics.launchers"]="Launchers", ["diagnostics.roots"]="Settings roots", ["diagnostics.check.translationStore"]="TranslationStore", ["diagnostics.check.exactStore"]="ExactStringStore", ["diagnostics.check.contextOverrides"]="Context overrides", ["diagnostics.check.dynamicRules"]="Dynamic rules", ["diagnostics.check.collector"]="String collector", ["diagnostics.check.font"]="Font system", ["diagnostics.check.textures"]="TextureStore", ["diagnostics.check.audio"]="AudioStore", ["diagnostics.check.watcher"]="File watcher", ["diagnostics.check.settingsUi"]="Settings UI", ["diagnostics.check.harmony"]="Harmony patches", ["diagnostics.check.exports"]="Export directory", ["diagnostics.check.languageDirectory"]="Language directory", ["diagnostics.check.translatorCanvas"]="Extra Canvas", ["diagnostics.check.launcher"]="Launcher", ["diagnostics.check.settingsRoots"]="Settings root", ["status.diagnosticsRefreshed"]="Diagnostics refreshed.", ["status.diagnosticsCopied"]="Diagnostics copied.", ["status.diagnosticsExported"]="Diagnostics exported.",
        ["translator.preserved"]="Explicitly preserved",
        ["qa.summary"]="QA SUMMARY", ["qa.checks"]="QUALITY CHECKS", ["qa.issues"]="FINDINGS", ["qa.actions"]="ACTIONS", ["qa.run"]="Run full QA", ["qa.exportReport"]="Export report", ["qa.exportUnresolved"]="Export unresolved", ["qa.openExports"]="Open exports", ["qa.copySummary"]="Copy summary", ["qa.notScanned"]="The QA scan has not run yet.", ["qa.overall"]="Overall status", ["qa.errors"]="Errors", ["qa.warnings"]="Warnings", ["qa.info"]="Information", ["qa.exact"]="Exact translations", ["qa.dynamic"]="Dynamic rules", ["qa.contexts"]="Context overrides", ["qa.runtime"]="Observed strings", ["qa.unknown"]="Unknown", ["qa.lastScan"]="Last scan", ["qa.noImportantIssues"]="No important issues found.", ["qa.status.pass"]="PASS", ["qa.status.warn"]="WARN", ["qa.status.fail"]="FAIL", ["qa.status.info"]="INFO", ["qa.status.na"]="N/A", ["qa.check.json"]="JSON integrity", ["qa.check.placeholders"]="Placeholders", ["qa.check.markup"]="TMP tags", ["qa.check.dynamic"]="Dynamic rules", ["qa.check.conflicts"]="Duplicates and conflicts", ["qa.check.cjk"]="CJK residue", ["qa.check.whitespace"]="Whitespace and controls", ["qa.check.length"]="Length risk", ["qa.check.encoding"]="Encoding", ["qa.check.textures"]="Texture manifest", ["qa.check.audio"]="Audio manifest", ["qa.check.paths"]="Pack paths", ["qa.check.contamination"]="Source and rendered data", ["status.qaComplete"]="QA scan completed.", ["status.qaExported"]="QA report exported.", ["status.qaSummaryCopied"]="QA summary copied.",
        ["translator.settings"]="TRANSLATOR SETTINGS", ["translator.session"]="CURRENT SESSION", ["translator.actions"]="QUICK ACTIONS", ["translator.exports"]="EXPORT", ["translator.mode"]="Translator mode", ["translator.debug"]="Detailed logging", ["translator.autoReload"]="Auto-reload files", ["translator.validateBeforeApply"]="Validate before applying", ["translator.captureUnknown"]="Capture unknown text", ["translator.autoExport"]="Auto-export on screen change", ["translator.detailedContext"]="Detailed context", ["translator.reloadNow"]="Reload now", ["translator.refreshCurrentScreen"]="Refresh current screen", ["translator.clearCapture"]="Clear capture", ["translator.copySessionSummary"]="Copy summary", ["translator.exportUntranslated"]="Export untranslated", ["translator.exportCurrentScreen"]="Export current screen", ["translator.exportSession"]="Export session", ["translator.openExports"]="Open exports", ["translator.currentContext"]="Current context", ["translator.scene"]="Observed scene", ["translator.uniqueSeen"]="Unique strings seen", ["translator.runtimeTranslated"]="Translated at runtime", ["translator.knownUntranslated"]="Known untranslated", ["translator.runtimeUnknown"]="Runtime unknown", ["translator.sessionUnknown"]="Captured this session", ["translator.watchedFiles"]="Watched files", ["translator.lastChange"]="Last change", ["translator.lastAutoReload"]="Last auto-reload", ["translator.watcher"]="Watcher status", ["translator.shortcutsInfo"]="Insert — translation  •  PageUp — reload  •  PageDown — export\nF8 / F9 / F10 — unused by the translator", ["translator.watcherActive"]="ACTIVE", ["translator.watcherDisabled"]="DISABLED", ["translator.watcherError"]="ERROR", ["status.autoReloadEnabled"]="Auto-reload enabled.", ["status.autoReloadDisabled"]="Auto-reload disabled.", ["status.settingSaved"]="Setting saved.", ["status.screenRefreshed"]="Current screen refreshed.", ["status.captureCleared"]="Capture cleared.", ["status.summaryCopied"]="Session summary copied.", ["status.untranslatedExported"]="Untranslated text exported.", ["status.sessionExported"]="Session exported.", ["status.autoReloaded"]="Translations reloaded automatically.",
        ["content.activePackSection"]="ACTIVE PACK", ["content.reloadSection"]="RELOAD", ["content.lastReloadSection"]="LAST RELOAD", ["content.foldersSection"]="FOLDERS", ["content.activeLanguage"]="Active language", ["content.folder"]="Folder", ["content.primaryFont"]="Primary font", ["content.fallback"]="Fallback", ["content.exact"]="Exact translations", ["content.dynamic"]="Dynamic rules", ["content.textures"]="Mapped textures", ["content.audio"]="Mapped audio", ["content.installedLocales"]="Installed languages", ["content.result"]="Result", ["content.time"]="Time", ["content.duration"]="Duration", ["content.files"]="Files processed", ["content.errors"]="Errors", ["content.never"]="Not run yet", ["content.pass"]="PASS", ["content.fail"]="FAIL", ["content.milliseconds"]="ms", ["actions.reloadTexts"]="Reload texts", ["actions.openTexturesFolder"]="Open textures", ["actions.openAudioFolder"]="Open audio", ["status.reloadPreserved"]="Reload failed — previous translation preserved.",
        ["common.enabled"]="Enabled", ["common.disabled"]="Disabled", ["general.languageSection"]="LANGUAGE", ["general.translationSection"]="TRANSLATION", ["general.interfaceSection"]="INTERFACE", ["general.statusSection"]="GENERAL STATUS", ["general.language"]="Language", ["general.translation"]="Text translation", ["general.font"]="Custom font", ["general.textures"]="Translated textures", ["general.audio"]="Custom audio", ["general.notifications"]="Interface notifications", ["general.uiScale"]="Interface scale", ["general.pack"]="Pack", ["general.version"]="Version",
        ["translator"]="Translator Mode", ["translatorHint"]="PageDown: export text and contexts", ["texts"]="Texts", ["languages"]="Languages", ["title"]="Language Settings", ["language"]="Language", ["translation"]="Translation", ["font"]="Custom font", ["textures"]="Translated textures", ["audio"]="Custom audio", ["reload"]="Reload", ["export"]="Export texts", ["close"]="Close", ["on"]="Enabled", ["off"]="Disabled", ["translationEnabled"]="Translation enabled", ["translationDisabled"]="Translation disabled", ["reloaded"]="Translations reloaded", ["reloadFailed"]="Failed to reload translations", ["exported"]="Translation diagnostics exported",
        ["menu.languages"]="Languages", ["menu.title"]="Translator Settings", ["tabs.qa"]="QA", ["common.close"]="Close", ["settings.title"]="Translator Settings", ["settings.language"]="Language", ["settings.translation"]="Text translation", ["settings.font"]="Custom font", ["settings.textures"]="Translated textures", ["settings.audio"]="Custom audio", ["settings.translatorMode"]="Translator mode", ["settings.debugLogging"]="Debug logging", ["settings.enabled"]="Enabled", ["settings.disabled"]="Disabled", ["settings.enabledPlural"]="Enabled", ["settings.disabledPlural"]="Disabled", ["settings.enabledMasculine"]="Enabled", ["settings.disabledMasculine"]="Disabled", ["settings.reload"]="Reload translation", ["settings.export"]="Export diagnostics", ["settings.close"]="Close", ["settings.packStatus"]="Pack loaded", ["tabs.general"]="General", ["tabs.content"]="Content", ["tabs.translator"]="Translator", ["tabs.diagnostics"]="Diagnostics", ["sections.language"]="LANGUAGE", ["sections.translation"]="TRANSLATION", ["sections.status"]="GENERAL STATUS", ["sections.fonts"]="FONTS AND CONTENT", ["sections.hotkeys"]="HOTKEYS", ["actions.reloadAll"]="Reload all", ["actions.reloadFonts"]="Reload fonts", ["actions.reloadTextures"]="Reload textures", ["actions.reloadAudio"]="Reload audio", ["actions.exportUntranslated"]="Export untranslated", ["actions.exportDiagnostics"]="Export diagnostics", ["actions.exportCurrentScene"]="Export current screen", ["actions.openLocaleFolder"]="Open locale folder", ["actions.openExportFolder"]="Open exports", ["actions.openModFolder"]="Open mod folder", ["actions.openLogs"]="Open logs", ["status.reloaded"]="Translations reloaded", ["status.reloadFailed"]="Failed to reload translations", ["status.exported"]="Diagnostics exported", ["status.sceneExported"]="Current screen exported", ["status.folderOpened"]="Folder opened", ["status.actionFailed"]="Action failed; see the log", ["status.onlyLocale"]="Only complete language installed", ["stats.version"]="Translator version", ["stats.gameVersion"]="Game version", ["stats.unityVersion"]="Unity version", ["stats.melonVersion"]="MelonLoader version", ["stats.locale"]="Locale", ["stats.exact"]="Exact", ["stats.dynamic"]="Dynamic", ["stats.rejected"]="Rejected", ["stats.warnings"]="Warnings", ["stats.known"]="Known untranslated", ["stats.unknown"]="Unknown runtime", ["stats.font"]="Primary font", ["stats.fallbackFonts"]="Fallback fonts", ["stats.textureMappings"]="Texture mappings", ["stats.audioMappings"]="Audio mappings", ["stats.translatorCanvas"]="Translator canvas", ["stats.context"]="Visible context", ["hotkeys.toggleTranslation"]="Toggle translation", ["hotkeys.reload"]="Reload", ["hotkeys.export"]="Export"
    };
    public static string Get(string locale,string key) =>
        (Overrides.TryGetValue(key,out var custom) || Overrides.TryGetValue("mod."+key,out custom) || Overrides.TryGetValue("mod.settings."+key,out custom)) ? custom :
        locale == "pt-BR" && Portuguese.TryGetValue(key,out var text) ? text : English.TryGetValue(key,out text) ? text : key;
}
